repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.2
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies:
          - pandas-stubs
          - boto3-stubs
          - types-aioboto3
          - scikit-learn-stubs
          - types-orjson
          - pytest
